// <auto-generated />
using System;
using MARS.Alerts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MARS.Alerts.Data.Migrations
{
    [DbContext(typeof(AlertsDbContext))]
    [Migration("20260930192839_SeedLegacyAlerts")]
    partial class SeedLegacyAlerts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("alerts")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MARS.Alerts.Entities.AdhdLayoutConfig", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DvdLogosCount")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowBreakingNews")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowCatisa")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowDVDLogos")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowFitnessVideo")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowGTAVideo")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowHydraulicMobileVideo")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowLOFIGirl")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowMukbangVideo")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowQuiz")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowRainEffect")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowSlimeVideo")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowStreamerVideo")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowSurfer")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowTimer")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AdhdLayoutConfig", "alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
