<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MARS.WaifuGacha</RootNamespace>
    <NoWarn>$(NoWarn);CS9113</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ShikimoriSharp" />
    <PackageReference Include="TwitchLib.Client" />
    <PackageReference Include="TwitchLib.Client.Models" />
    <PackageReference Include="TwitchLib.EventSub.Core" />
    <PackageReference Include="TwitchLib.EventSub.Websockets" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MARS.Shared\MARS.Shared.csproj" />
  </ItemGroup>

</Project>
