// <auto-generated />
using System;
using MARS.MediaStorage.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MARS.MediaStorage.Data.Migrations;

[DbContext(typeof(MediaStorageDbContext))]
partial class MediaStorageDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("mediastorage")
            .HasAnnotation("ProductVersion", "10.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("MARS.MediaStorage.Entities.MediaStorageEntry", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<string>("ContentHash")
                .HasColumnType("text");

            b.Property<DateTimeOffset?>("DeletedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<string>("Extension")
                .IsRequired()
                .HasColumnType("text");

            b.Property<string>("FileName")
                .IsRequired()
                .HasColumnType("text");

            b.Property<DateTimeOffset?>("LastDownloadedAt")
                .HasColumnType("timestamp with time zone");

            b.Property<int>("MediaType")
                .HasColumnType("integer");

            b.Property<string>("OriginalPath")
                .HasColumnType("text");

            b.Property<string>("Path")
                .IsRequired()
                .HasColumnType("text");

            b.Property<long>("SizeBytes")
                .HasColumnType("bigint");

            b.Property<DateTimeOffset>("UploadedAt")
                .HasColumnType("timestamp with time zone");

            b.HasKey("Id");

            b.HasIndex("DeletedAt");

            b.HasIndex("Path")
                .IsUnique();

            b.ToTable("MediaEntries", "mediastorage");
        });

        modelBuilder.Entity("MARS.MediaStorage.Entities.MemeOrder", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.Property<string>("FilePath")
                .IsRequired()
                .HasMaxLength(2147483647)
                .HasColumnType("text");

            b.Property<bool>("IsFileNotConvertable")
                .HasColumnType("boolean");

            b.Property<int?>("MemeTypeId")
                .HasColumnType("integer");

            b.Property<int>("Order")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Order"));

            b.HasKey("Id");

            b.HasIndex("MemeTypeId");

            b.ToTable("RandomMemeOrder", "mediastorage");
        });

        modelBuilder.Entity("MARS.MediaStorage.Entities.MemeType", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("integer");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

            b.Property<string>("FolderPath")
                .IsRequired()
                .HasMaxLength(2147483647)
                .HasColumnType("text");

            b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnType("character varying(50)");

            b.HasKey("Id");

            b.ToTable("RandomMemeType", "mediastorage");

            b.HasData(
                new
                {
                    Id = 3,
                    FolderPath = "Alerts/zvik",
                    Name = "Random Sound"
                },
                new
                {
                    Id = 2,
                    FolderPath = "Alerts/random_meme",
                    Name = "Random Meme"
                });
        });

        modelBuilder.Entity("MARS.Shared.Models.Media.MediaInfo", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            b.HasKey("Id");

            b.ToTable("Alerts", "mediastorage");
        });

        modelBuilder.Entity("MARS.MediaStorage.Entities.MemeOrder", b =>
        {
            b.HasOne("MARS.MediaStorage.Entities.MemeType", "Type")
                .WithMany()
                .HasForeignKey("MemeTypeId");

            b.Navigation("Type");
        });

        modelBuilder.Entity("MARS.Shared.Models.Media.MediaInfo", b =>
        {
            b.OwnsOne("MARS.Shared.Models.Media.MediaFileInfo", "FileInfo", b1 =>
            {
                b1.Property<Guid>("MediaInfoId")
                    .HasColumnType("uuid");

                b1.Property<string>("Extension")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("FileInfo_Extension");

                b1.Property<string>("FileName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("FileInfo_FileName");

                b1.Property<string>("FilePath")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("FileInfo_LocalFilePath");

                b1.Property<bool>("IsFileNotConvertable")
                    .HasColumnType("boolean")
                    .HasColumnName("FileInfo_IsFileNotConvertable");

                b1.Property<bool>("IsLocalFile")
                    .HasColumnType("boolean")
                    .HasColumnName("FileInfo_IsLocal");

                b1.Property<string>("Type")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("FileInfo_Type");

                b1.HasKey("MediaInfoId");

                b1.ToTable("Alerts", "mediastorage");

                b1.WithOwner()
                    .HasForeignKey("MediaInfoId");
            });

            b.OwnsOne("MARS.Shared.Models.Media.MediaMetaInfo", "MetaInfo", b1 =>
            {
                b1.Property<Guid>("MediaInfoId")
                    .HasColumnType("uuid");

                b1.Property<string>("DisplayName")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("MetaInfo_DisplayName");

                b1.Property<int>("Duration")
                    .HasColumnType("integer")
                    .HasColumnName("MetaInfo_Duration");

                b1.Property<bool>("IsEnabled")
                    .HasColumnType("boolean");

                b1.Property<bool>("IsFreezeRequired")
                    .HasColumnType("boolean");

                b1.Property<bool>("IsLooped")
                    .HasColumnType("boolean")
                    .HasColumnName("MetaInfo_IsLooped");

                b1.Property<int>("Priority")
                    .HasColumnType("integer")
                    .HasColumnName("MetaInfo_Priority");

                b1.Property<Guid?>("TwitchGuid")
                    .HasColumnType("uuid");

                b1.Property<int>("TwitchPointsCost")
                    .HasColumnType("integer")
                    .HasColumnName("MetaInfo_TwitchPointsCost");

                b1.Property<bool>("Vip")
                    .HasColumnType("boolean")
                    .HasColumnName("MetaInfo_VIP");

                b1.Property<int>("Volume")
                    .HasColumnType("integer");

                b1.HasKey("MediaInfoId");

                b1.ToTable("Alerts", "mediastorage");

                b1.WithOwner()
                    .HasForeignKey("MediaInfoId");
            });

            b.OwnsOne("MARS.Shared.Models.Media.MediaPositionInfo", "PositionInfo", b1 =>
            {
                b1.Property<Guid>("MediaInfoId")
                    .HasColumnType("uuid");

                b1.Property<int>("Height")
                    .HasColumnType("integer")
                    .HasColumnName("PositionInfo_Height");

                b1.Property<bool>("IsHorizontalCenter")
                    .HasColumnType("boolean")
                    .HasColumnName("PositionInfo_IsHorizontalCenter");

                b1.Property<bool>("IsProportion")
                    .HasColumnType("boolean")
                    .HasColumnName("PositionInfo_IsProportion");

                b1.Property<bool>("IsResizeRequires")
                    .HasColumnType("boolean")
                    .HasColumnName("PositionInfo_IsResizeRequires");

                b1.Property<bool>("IsRotated")
                    .HasColumnType("boolean")
                    .HasColumnName("PositionInfo_IsRotated");

                b1.Property<bool>("IsUseOriginalWidthAndHeight")
                    .HasColumnType("boolean");

                b1.Property<bool>("IsVerticallCenter")
                    .HasColumnType("boolean")
                    .HasColumnName("PositionInfo_IsVerticallCenter");

                b1.Property<bool>("RandomCoordinates")
                    .HasColumnType("boolean")
                    .HasColumnName("PositionInfo_RandomCoordinates");

                b1.Property<int>("Rotation")
                    .HasColumnType("integer")
                    .HasColumnName("PositionInfo_Rotation");

                b1.Property<int>("Width")
                    .HasColumnType("integer")
                    .HasColumnName("PositionInfo_Width");

                b1.Property<int>("XCoordinate")
                    .HasColumnType("integer")
                    .HasColumnName("PositionInfo_XCoordinate");

                b1.Property<int>("YCoordinate")
                    .HasColumnType("integer")
                    .HasColumnName("PositionInfo_YCoordinate");

                b1.HasKey("MediaInfoId");

                b1.ToTable("Alerts", "mediastorage");

                b1.WithOwner()
                    .HasForeignKey("MediaInfoId");
            });

            b.OwnsOne("MARS.Shared.Models.Media.MediaStylesInfo", "StylesInfo", b1 =>
            {
                b1.Property<Guid>("MediaInfoId")
                    .HasColumnType("uuid");

                b1.Property<bool>("IsBorder")
                    .HasColumnType("boolean")
                    .HasColumnName("StylesInfo_IsBorder");

                b1.Property<bool>("IsShowLetterbox")
                    .HasColumnType("boolean")
                    .HasColumnName("StylesInfo_IsShowLetterbox");

                b1.HasKey("MediaInfoId");

                b1.ToTable("Alerts", "mediastorage");

                b1.WithOwner()
                    .HasForeignKey("MediaInfoId");
            });

            b.OwnsOne("MARS.Shared.Models.Media.MediaTextInfo", "TextInfo", b1 =>
            {
                b1.Property<Guid>("MediaInfoId")
                    .HasColumnType("uuid");

                b1.Property<char?>("KeyWordSybmolDelimiter")
                    .HasColumnType("character(1)");

                b1.Property<string>("KeyWordsColor")
                    .HasColumnType("text")
                    .HasColumnName("TextInfo_KeyWordsColor");

                b1.Property<string>("Text")
                    .HasColumnType("text")
                    .HasColumnName("TextInfo_Text");

                b1.Property<string>("TextColor")
                    .HasColumnType("text")
                    .HasColumnName("TextInfo_TextColor");

                b1.Property<string>("TriggerWord")
                    .HasColumnType("text")
                    .HasColumnName("TextInfo_TriggerWord");

                b1.HasKey("MediaInfoId");

                b1.ToTable("Alerts", "mediastorage");

                b1.WithOwner()
                    .HasForeignKey("MediaInfoId");
            });

            b.Navigation("FileInfo")
                .IsRequired();

            b.Navigation("MetaInfo")
                .IsRequired();

            b.Navigation("PositionInfo")
                .IsRequired();

            b.Navigation("StylesInfo")
                .IsRequired();

            b.Navigation("TextInfo")
                .IsRequired();
        });
#pragma warning restore 612, 618
    }
}
