<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MARS.TTS</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="SevenTV-lib" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MARS.Shared\MARS.Shared.csproj" />
  </ItemGroup>

</Project>
