<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MARS.MediaStorage</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FFMpegCore" />
    <PackageReference Include="Telegram.Bot" />
    <PackageReference Include="Ben.Demystifier" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MARS.Shared\MARS.Shared.csproj" />
  </ItemGroup>

</Project>
