// <auto-generated />
using System;
using MARS.Scoreboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MARS.Scoreboard.Data.Migrations
{
    [DbContext(typeof(ScoreboardDbContext))]
    partial class ScoreboardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("scoreboard")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MARS.Scoreboard.Entities.ScoreboardLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FlagSize")
                        .HasColumnType("integer");

                    b.Property<int>("HeaderHeight")
                        .HasColumnType("integer");

                    b.Property<int>("HeaderLeft")
                        .HasColumnType("integer");

                    b.Property<int>("HeaderTop")
                        .HasColumnType("integer");

                    b.Property<int>("HeaderWidth")
                        .HasColumnType("integer");

                    b.Property<int>("Padding")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerBarHeight")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerBarWidth")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersLeft")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersRight")
                        .HasColumnType("integer");

                    b.Property<int>("PlayersTop")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreSize")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreboardStateId")
                        .HasColumnType("integer");

                    b.Property<bool>("ShowFlags")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowHeader")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowSponsors")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowTags")
                        .HasColumnType("boolean");

                    b.Property<int>("Spacing")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScoreboardStateId")
                        .IsUnique();

                    b.ToTable("ScoreboardLayouts", "scoreboard");
                });

            modelBuilder.Entity("MARS.Scoreboard.Entities.ScoreboardPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Final")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreboardStateId")
                        .HasColumnType("integer");

                    b.Property<string>("Sponsor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScoreboardStateId");

                    b.ToTable("ScoreboardPlayers", "scoreboard");
                });

            modelBuilder.Entity("MARS.Scoreboard.Entities.ScoreboardState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimationDuration")
                        .HasColumnType("integer");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BorderColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FightModeColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FightRule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("MainColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerNamesColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScoreColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TournamentTitleColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ScoreboardStates", "scoreboard");
                });

            modelBuilder.Entity("MARS.Scoreboard.Entities.ScoreboardLayout", b =>
                {
                    b.HasOne("MARS.Scoreboard.Entities.ScoreboardState", "ScoreboardState")
                        .WithOne("Layout")
                        .HasForeignKey("MARS.Scoreboard.Entities.ScoreboardLayout", "ScoreboardStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoreboardState");
                });

            modelBuilder.Entity("MARS.Scoreboard.Entities.ScoreboardPlayer", b =>
                {
                    b.HasOne("MARS.Scoreboard.Entities.ScoreboardState", "ScoreboardState")
                        .WithMany("Players")
                        .HasForeignKey("ScoreboardStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoreboardState");
                });

            modelBuilder.Entity("MARS.Scoreboard.Entities.ScoreboardState", b =>
                {
                    b.Navigation("Layout");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
