// <auto-generated />
using System;
using MARS.TwitchCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MARS.TwitchCore.Data.Migrations
{
    [DbContext(typeof(TwitchDbContext))]
    partial class TwitchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("twitch")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MARS.TwitchCore.Entities.AutoMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AutoMessages", "twitch");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.ChannelRewardRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("text");

                    b.Property<int>("Cost")
                        .HasColumnType("integer");

                    b.Property<int?>("GlobalCooldownSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGlobalCooldownEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMaxPerStreamEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMaxPerUserPerStreamEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUserInputRequired")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxPerStream")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxPerUserPerStream")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MediaInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<bool>("ShouldRedemptionsSkipRequestQueue")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TwitchRewardId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ChannelRewards", "twitch");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.FollowerInfo", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.ToTable("FollowersEntitys", "twitch");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.FumoUser", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TwitchId");

                    b.ToTable("FumoUsers", "twitch");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.HelloVideosUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastTimeNotif")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MediaInfoId")
                        .HasColumnType("uuid");

                    b.Property<string>("TwitchId")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TwitchId");

                    b.ToTable("HelloVideosUsers", "twitch");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.Husband", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsPrivated")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastWeddingCongratulatedMonths")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WhenPrivated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TwitchId");

                    b.ToTable("Husbands", "twitch");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.RollCooldown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastRollTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RollType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TwitchUserId", "RollType")
                        .IsUnique();

                    b.ToTable("RollCooldowns", "twitch");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.RootState", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("RootState", "twitch");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.SevenTvEmote", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LoadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Name");

                    b.ToTable("SevenTvEmotes", "twitch");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.TokenInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("ExpiresIn")
                        .HasColumnType("interval");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("WhenCreated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TwitchToken", "twitch");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.TwitchLeaderboardUser", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RussianRouletteWins")
                        .HasColumnType("integer");

                    b.Property<int>("RussianRouletteWinsWithWaifu")
                        .HasColumnType("integer");

                    b.Property<int>("TriviaWins")
                        .HasColumnType("integer");

                    b.Property<int>("TriviaWinsWithWaifus")
                        .HasColumnType("integer");

                    b.HasKey("TwitchId");

                    b.ToTable("TwitchLeaderboardUsers", "twitch");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.TwitchUser", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TwitchId");

                    b.Property<string>("AliasNickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChatColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("FollowedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsInBlockList")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsModerator")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVip")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TwitchId");

                    b.ToTable("TwitchUsers", "twitch");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.FollowerInfo", b =>
                {
                    b.HasOne("MARS.TwitchCore.Entities.TwitchUser", "TwitchUser")
                        .WithOne()
                        .HasForeignKey("MARS.TwitchCore.Entities.FollowerInfo", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TwitchUser");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.FumoUser", b =>
                {
                    b.HasOne("MARS.TwitchCore.Entities.TwitchUser", "TwitchUser")
                        .WithMany()
                        .HasForeignKey("TwitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TwitchUser");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.HelloVideosUsers", b =>
                {
                    b.HasOne("MARS.TwitchCore.Entities.TwitchUser", "TwitchUser")
                        .WithMany()
                        .HasForeignKey("TwitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TwitchUser");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.Husband", b =>
                {
                    b.HasOne("MARS.TwitchCore.Entities.TwitchUser", "TwitchUser")
                        .WithOne()
                        .HasForeignKey("MARS.TwitchCore.Entities.Husband", "TwitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TwitchUser");
                });

            modelBuilder.Entity("MARS.TwitchCore.Entities.TwitchLeaderboardUser", b =>
                {
                    b.HasOne("MARS.TwitchCore.Entities.TwitchUser", "TwitchUser")
                        .WithMany()
                        .HasForeignKey("TwitchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TwitchUser");
                });
#pragma warning restore 612, 618
        }
    }
}
