<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MARS.OBS</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MARS.Shared\MARS.Shared.csproj" />
  </ItemGroup>

</Project>
