// <auto-generated />
using System;
using MARS.WaifuGacha.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MARS.WaifuGacha.Data.Migrations
{
    [DbContext(typeof(WaifuDbContext))]
    [Migration("20260921225337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("waifu")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MARS.WaifuGacha.Entities.AutoHelloMessage", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Guid");

                    b.ToTable("AutoHelloMessages", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.Frog", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Pid"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Family")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Habits")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastOrder")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<string>("RussianName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("WhenAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Pid");

                    b.ToTable("Frogs", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.Fumo", b =>
                {
                    b.Property<int>("MfcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MfcId"));

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CharacterTranslit")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("LastOrder")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<string>("Origin")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("RatingCount")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("WhenAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MfcId");

                    b.ToTable("Fumos", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.Husband", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasColumnType("text");

                    b.Property<bool>("IsPrivated")
                        .HasColumnType("boolean");

                    b.Property<int?>("LastWeddingCongratulatedMonths")
                        .HasColumnType("integer");

                    b.Property<long>("OrderCount")
                        .HasColumnType("bigint");

                    b.Property<string>("WaifuBrideId")
                        .HasColumnType("text");

                    b.Property<string>("WaifuRollId")
                        .HasColumnType("text");

                    b.Property<DateTime>("WhenOrdered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WhenPrivated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TwitchId");

                    b.ToTable("Husbands", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.HusbandAutoHello", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HusbandId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Guid");

                    b.HasIndex("HusbandId")
                        .IsUnique();

                    b.ToTable("HusbandAutoHelloCooldowns", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.HusbandCoolDown", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HusbandId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Guid");

                    b.HasIndex("HusbandId")
                        .IsUnique();

                    b.ToTable("HusbandCoolDowns", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.MikuModule", b =>
                {
                    b.Property<int>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PageId"));

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Designer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("JapaneseName")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("LastOrder")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<string>("Songs")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("WhenAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PageId");

                    b.ToTable("MikuModules", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.MikuMondayActivation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MikuMondayTrackId")
                        .HasColumnType("integer");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeekOfYear")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MikuMondayTrackId");

                    b.ToTable("MikuMondayActivations", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.MikuMondayTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("BaseTrackInfoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MikuMondayTracks", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.RollCooldown", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastRollTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RollType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("RollCooldowns", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.RootState", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("RootState", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.UserFumoCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstObtained")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FumoMfcId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastObtained")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UserFumoCollections", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.UserMikuCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstObtained")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastObtained")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MikuPageId")
                        .HasColumnType("integer");

                    b.Property<string>("TwitchUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UserMikuCollections", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.Waifu", b =>
                {
                    b.Property<string>("ShikiId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("Age")
                        .HasColumnType("bigint");

                    b.Property<string>("Anime")
                        .HasColumnType("text");

                    b.Property<Guid?>("AudioId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsPrivated")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastOrder")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Manga")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrderCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("WhenAdded")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ShikiId");

                    b.HasIndex("AudioId");

                    b.ToTable("Waifus", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.WaifuRollAudio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AudioData")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("WaifuRollAudios", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.WaifuRollGuarantee", b =>
                {
                    b.Property<string>("TwitchId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastRoll")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RollCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TwitchId");

                    b.ToTable("WaifuRollGuarantees", "waifu");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.HusbandAutoHello", b =>
                {
                    b.HasOne("MARS.WaifuGacha.Entities.Husband", "Husband")
                        .WithOne("HusbandGreetings")
                        .HasForeignKey("MARS.WaifuGacha.Entities.HusbandAutoHello", "HusbandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Husband");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.HusbandCoolDown", b =>
                {
                    b.HasOne("MARS.WaifuGacha.Entities.Husband", "Husband")
                        .WithOne("HusbandCoolDown")
                        .HasForeignKey("MARS.WaifuGacha.Entities.HusbandCoolDown", "HusbandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Husband");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.MikuMondayActivation", b =>
                {
                    b.HasOne("MARS.WaifuGacha.Entities.MikuMondayTrack", "MikuMondayTrack")
                        .WithMany()
                        .HasForeignKey("MikuMondayTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MikuMondayTrack");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.Waifu", b =>
                {
                    b.HasOne("MARS.WaifuGacha.Entities.WaifuRollAudio", "Audio")
                        .WithMany()
                        .HasForeignKey("AudioId");

                    b.Navigation("Audio");
                });

            modelBuilder.Entity("MARS.WaifuGacha.Entities.Husband", b =>
                {
                    b.Navigation("HusbandCoolDown");

                    b.Navigation("HusbandGreetings");
                });
#pragma warning restore 612, 618
        }
    }
}
