// <auto-generated />
using System;
using MARS.Telegram.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MARS.Telegram.Data.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20260922000612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("chat")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MARS.Telegram.Entities.ChannelProcessingState", b =>
                {
                    b.Property<long>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ChannelId"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("MessagesHash")
                        .HasColumnType("bigint");

                    b.Property<int>("OffsetId")
                        .HasColumnType("integer");

                    b.HasKey("ChannelId");

                    b.ToTable("ChannelProcessingStates", "chat");
                });

            modelBuilder.Entity("MARS.Telegram.Entities.RootState", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("RootState", "chat");
                });

            modelBuilder.Entity("MARS.Telegram.Entities.TelegramDiscordChannelBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordChannelId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("TelegramChannelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TelegramChannelId", "DiscordChannelId")
                        .IsUnique();

                    b.ToTable("TelegramDiscordChannelBindings", "chat");
                });

            modelBuilder.Entity("MARS.Telegram.Entities.TelegramDiscordChannelState", b =>
                {
                    b.Property<long>("TelegramChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TelegramChannelId"));

                    b.Property<int>("LastProcessedMessageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TelegramChannelId");

                    b.ToTable("TelegramDiscordChannelStates", "chat");
                });

            modelBuilder.Entity("MARS.Telegram.Entities.TelegramUpdateReceiverOffset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Offset")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TelegramUpdateReceiverOffsets", "chat");
                });

            modelBuilder.Entity("MARS.Telegram.Entities.TelegramUser", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ByeByeLastMessageTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("ByeByeServiceNotification")
                        .HasColumnType("boolean");

                    b.Property<bool>("GenshinImpactDailyNotif")
                        .HasColumnType("boolean");

                    b.Property<bool>("HonkaiNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRandomMemeSendler")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastTimeMessage")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PyroAlertsAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("RaidHelper")
                        .HasColumnType("boolean");

                    b.Property<bool>("StreamUpNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("ZenlessZoneZeroDailyNotif")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("TelegramUsers", "chat");
                });

            modelBuilder.Entity("MARS.Telegram.Entities.WTelegramSession", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Name");

                    b.ToTable("WTelegramSessions", "chat");
                });
#pragma warning restore 612, 618
        }
    }
}
